.TH ccraw 1 "date not needed" "too lazy to version" "User Commands"
.SH NAME
\f\*[B-Font]ccraw\fP
\- crows in the terminal

.SH SYNOPSIS
.B ccraw
.RB [ \-flags ]
.RB [ \-flag
.RI [ value ]]
.RB [ \-\-option
.RI [ value ]]

.SH DESCRIPTION
Crows in the terminal. That is it. Do you need anything else?

.SH OPTIONS
.TP
.BR \-d ", " \-\-debug
Enable debugging. This option takes no arguments. Displays things like key events and other things. Used mainly for development.
.TP
\fB\-C\fR [\fInum\fR], \fB--crows\fR [\fInum\fR]
Sets the starting amount of crows to \fInum\fR


.SH AUTHORS
.RI "Jenyyk / Rezyys / Jan Křivský: " "https://github.com/Jenyyk"

.SH LICENSE
Copyright (c) 2026 Jan Křivský. This program is licensed unde the MIT License. Additionally, all users of this program are required to have fun while using it :)

.SH BUGS
.RI "For bug reports please open an issue on github: " "https://github.com/Jenyyk/ccraw" 
